/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./src/components/Auth/index.vue')['default']
    AuthAll: typeof import('./src/components/AuthAll/index.vue')['default']
    EditGrade: typeof import('./src/components/EditGrade/index.vue')['default']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FileUpload: typeof import('./src/components/FileUpload/index.vue')['default']
    FilterSelect: typeof import('./src/components/FilterSelect/index.vue')['default']
    FilterTag: typeof import('./src/components/FilterTag/index.vue')['default']
    FixedActionBar: typeof import('./src/components/FixedActionBar/index.vue')['default']
    GradeInput: typeof import('./src/components/GradeInput/index.vue')['default']
    GradeTable: typeof import('./src/components/GradeTable/index.vue')['default']
    ImagePreview: typeof import('./src/components/ImagePreview/index.vue')['default']
    ImagesUpload: typeof import('./src/components/ImagesUpload/index.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload/index.vue')['default']
    ImportExcel: typeof import('./src/components/ImportExcel/index.vue')['default']
    NotAllowed: typeof import('./src/components/NotAllowed/index.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader/index.vue')['default']
    PageMain: typeof import('./src/components/PageMain/index.vue')['default']
    PcasCascader: typeof import('./src/components/PcasCascader/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    SystemInfo: typeof import('./src/components/SystemInfo/index.vue')['default']
    Trend: typeof import('./src/components/Trend/index.vue')['default']
  }
}
